<a href="https://colab.research.google.com/github/sofa-tsy/LMS-ML-/blob/main/%D0%9B%D0%BE%D0%B3%D0%B8%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D1%80%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B8%D1%8F_LMS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Задача 1: Прогнозирование вероятности покупки товара в интернет-магазине

Студент B посетил интернет-магазин и просмотрел товары из категории "Электроника", сумма его предыдущей покупки составила 1500 рублей, а длительность сессии - 20 минут.

У нас есть обученная модель логистической регрессии с коэффициентами:

сумма покупки - 0.002

категория "Электроника" - 0.5

длительность сессии - 0.1

свободный коэффициент - -5

Получите вероятность покупки студентом B в интернет-магазине и укажите ответ, округлив его до второго знака после точки.

In [ ]:
import math

model = 0.002*1500 + 0.5 + 0.1*20 - 5
print(model)

print(round(1/(1 + math.exp(-model)),2))

0.5
0.62

## Задача 2
Сделайте разбиение на обучение и тест с соотношением 80/20 и random_state=10.

Целевой признак grade: 0 - оценка ниже среднего, 1 - оценка выше среднего.

Обучите логистическую регрессию из sklearn на базовых параметрах для решения поставленной задачи и укажите вес, который получился после обучения модели, при признаке studytime, округлив его до второго знака после точки.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('student.csv')
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,grade
count,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000
mean,16.744222,2.514638,2.306626,1.568567,1.930663,0.221880,3.930663,3.180277,3.184900,1.502311,2.280431,3.536210,3.659476,1.244992
std,1.218138,1.134552,1.099931,0.748660,0.829510,0.593235,0.955717,1.051093,1.175766,0.924834,1.284380,1.446259,4.640759,0.430414
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000
25%,16.000000,2.000000,1.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,2.000000,0.000000,1.000000
50%,17.000000,2.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,2.000000,1.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,6.000000,1.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,32.000000,2.000000

In [ ]:
df['grade'].value_counts()

grade
1    490
2    159
Name: count, dtype: int64

In [ ]:
y = df['grade'].values
x = df.drop(columns = 'grade', axis = 1).values

x_train,x_test, y_train , y_test  = train_test_split(x,y,test_size = 0.2, random_state = 10)

model = LogisticRegression()
model.fit(x_train, y_train)

model.predict(x_test)

feature_names = df.drop(columns = 'grade', axis = 1).columns
coefficients = model.coef_[0]
# может получиться двумерный массив с несколькими строками если многоклассовая классификация

# coefficients
# Создаем DataFrame с весами признаков
weights_df = pd.DataFrame({
    'feature': feature_names,
    'weight': coefficients
})

weights_df

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

       feature    weight
0          age  0.183713
1         Medu  0.462795
2         Fedu  0.024887
3   traveltime -0.140848
4    studytime  0.382317
5     failures -1.330981
6       famrel  0.003150
7     freetime  0.051234
8        goout -0.018066
9         Dalc -0.665309
10        Walc  0.020348
11      health -0.135871
12    absences -0.055865

Вероятней всего (если у вас не отключены предупреждения) Python выдал

ConvergenceWarning: lbfgs failed to converge (status=1): STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.,

такое встречается, если в данных есть признаки разных масштабов. Давайте исправим это с помощью масштабирования данных через стандартизацию.

Обучите модель StandardScaler на тренировочной выборке.

Преобразуйте тренировочные и тестовые данных с помощью стандартизации

Укажите, какие диапазоны получились у признака age на тестовой выборке - значение min и max.

In [ ]:
scaler = StandardScaler()
scaler.fit(x_train)

x_train_scaler = scaler.transform(x_train)
x_test_scaler = scaler.transform(x_test)

x_test_scaler[:,0] # все строки, первыйы столбец, который отвечает за age

age_min = x_test_scaler[:,0].min()
age_max = x_test_scaler[:,0].max()

print(f"Минимальное значение: {age_min:.2f}")
print(f"Максимальное значение: {age_max:.2f}")

Минимальное значение: -1.47
Максимальное значение: 4.40

Обучите модель логистической регрессии с базовыми параметрами на стандартизованных данных и посчитайте метрику accuracy на тренировочной и тестовой выборках и укажите их, округлив до второго знака после точки.

In [ ]:
from sklearn.metrics import accuracy_score

model1 = LogisticRegression()
model1.fit(x_train_scaler, y_train)

y_test_pred_scal = model1.predict(x_test_scaler)
y_train_pred_scal = model1.predict(x_train_scaler)

print(f"Accuracy на тренировочной выборке: {accuracy_score(y_train, y_train_pred_scal ):.2f}")
print(f"Accuracy на тестовой выборке: {accuracy_score(y_test, y_test_pred_scal):.2f}")

Accuracy на тренировочной выборке: 0.76
Accuracy на тестовой выборке: 0.78

Возьмите НЕ масштабированные данные, т.к. сейчас будем их усложнять для более качественной модели.

Для удобства можете пользоваться pipeline из sklearn, в котором будут:

Модель полиномизации признаков до 4 степени PolynomialFeatures

Модель масштабирования данных StandardScaler

Логистическая регрессия БЕЗ регуляризации

По умолчанию в логистической регрессии в sklearn есть L2 регуляризация, чтобы её отключить, нужно поменять параметр penalty.

Обучите пайплайн на тренировочной выборке и посчитайте метрику accuracy на тренировочной и тестовой выборках и укажите их, округлив до второго знака после точки.

In [ ]:
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.pipeline import Pipeline

pipe = Pipeline([
    ('poly', PolynomialFeatures(degree=4, include_bias=False)),
    ('scaler', StandardScaler()),
    ('logreg', LogisticRegression(penalty= None)) # max_iter=100)  # значение по умолчанию
])

pipe.fit(x_train, y_train)

y_pipe_test_pred = pipe.predict(x_test)
y_pipe_train_pred = pipe.predict(x_train)

print(f"Accuracy на тренировочной выборке: {accuracy_score(y_train, y_pipe_train_pred ):.2f}")
print(f"Accuracy на тестовой выборке: {accuracy_score(y_test, y_pipe_test_pred ):.2f}")


# на тренировочной выше чем на тестовой - так не должно быть
#  это эффект переобучения

Accuracy на тренировочной выборке: 0.95
Accuracy на тестовой выборке: 0.68

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Снова вероятней всего (если у вас не отключены предупреждения) Python выдал ConvergenceWarning: lbfgs failed to converge (status=1): STOP: TOTAL NO. of ITERATIONS REACHED LIMIT., хотя масштабирование данных сделано, так же эту ошибку можно избежать, если увеличить количество итераций в логистической регрессии, увеличьте параметр max_iter до 600.

Так же метрика на тесте стала меньше, потому что модель переобучается, нужно и это исправить с помощью регуляризации.

Для удобства можете пользоваться pipeline из sklearn, в котором будут:

Модель полиномизации признаков до 4 степени PolynomialFeatures

Модель масштабирования данных StandardScaler

Логистическая регрессия с L2 регуляризацией

Сделайте перебор параметра C в логистической регрессии, который из себя представляет 1/коэффициент регуляризации. Значения C перебирайте из следующего списка: [0.0001, 0.001, 0.01, 0.1, 1].

Укажите, самую лучшую метрику на тесте, округлив её до второго знака после точки.

In [ ]:
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.pipeline import Pipeline

C = [0.0001, 0.001, 0.01, 0.1, 1]


for i in C:


  pipei = Pipeline([
      ('poly', PolynomialFeatures(degree=4, include_bias=False)),
      ('scaler', StandardScaler()),
      ('logreg', LogisticRegression(penalty = 'l2', C = i, max_iter= 600)) # max_iter=100)  # значение по умолчанию
  ])

  pipei.fit(x_train, y_train)

  y_pipei_test_pred = pipei.predict(x_test)
  y_pipei_train_pred = pipei.predict(x_train)

  # print(f"Accuracy на тренировочной выборке {i}: {accuracy_score(y_train, y_pipei_train_pred ):.2f}")
  print(f"Accuracy на тестовой выборке {i}: {accuracy_score(y_test, y_pipei_test_pred ):.2f}")

Accuracy на тестовой выборке 0.0001: 0.81
Accuracy на тестовой выборке 0.001: 0.78
Accuracy на тестовой выборке 0.01: 0.79
Accuracy на тестовой выборке 0.1: 0.78
Accuracy на тестовой выборке 1: 0.70

## Задача 3

Имеется датасет для чаевых для таксиста . Но мы возьмём немного измененную версию данных. Скачать датасет.

Сделайте разбиение на обучение и тест с соотношением 80/20 и random_state=10.

Целевой признак tip_class.

Обучите логистическую регрессию из sklearn с параметром max_iter=400 для решения поставленной задачи.

Изучите масштаб в данных и если это требуется примените StandardScaler.

Укажите метрики accuracy на тренировочной и тестовой выборках, округлив их до второго знака после точки.

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd


df = pd.read_csv('taxi.csv')
df

,trip_duration,distance_traveled,num_of_passengers,fare,miscellaneous_fees,total_fare,surge_applied,tip_class
0,748.0,2.75,1.0,75.00,6.300,105.300,0,over med
1,1187.0,3.43,1.0,105.00,13.200,142.200,0,over med
2,329.0,2.09,1.0,45.00,13.200,70.200,0,under med
3,355.0,1.74,1.0,45.00,26.625,71.625,1,low
4,1288.0,5.21,1.0,116.25,26.325,178.575,1,high
...,...,...,...,...,...,...,...,...
137160,729.0,2.49,1.0,75.00,6.200,97.200,0,under med
137161,1617.0,8.42,1.0,150.00,5.800,202.800,0,high
137162,438.0,1.29,1.0,48.75,34.575,95.325,1,under med
137163,571.0,2.82,1.0,63.75,6.000,69.750,0,low
137164,491.0,2.16,1.0,56.25,13.500,69.750,0,low

In [ ]:
df['tip_class'].value_counts()

tip_class
under med    35798
low          35289
high         34156
over med     31922
Name: count, dtype: int64

In [ ]:
x = df.drop(columns='tip_class', axis = 1).values
y = df['tip_class'].values

In [ ]:
pipe = Pipeline([

    ('scaler', StandardScaler()),
    ('logreg', LogisticRegression(max_iter=400))
])

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 10)

pipe.fit(x_train, y_train)

y_pipe_test_pred = pipe.predict(x_test)
y_pipe_train_pred = pipe.predict(x_train)

print(f"Accuracy на тренировочной выборке: {accuracy_score(y_train, y_pipe_train_pred ):.2f}")
print(f"Accuracy на тестовой выборке: {accuracy_score(y_test, y_pipe_test_pred ):.2f}")

Accuracy на тренировочной выборке: 0.96
Accuracy на тестовой выборке: 0.96

In [ ]:
y_pipe_test_pred

array(['low', 'low', 'under med', ..., 'over med', 'over med',
       'under med'], dtype=object)

Посчитайте, сколько получилось ошибочных предсказаний в процентном соотношении по каждому классу на тестовой выборке и укажите в ответе, округлив проценты до второго знака после точки.

Пример ответа:

low: 5.10% ошибочных предсказаний under med: 15.26% ошибочных предсказаний over med: 18.93% ошибочных предсказаний high: 6.24% ошибочных предсказаний

In [ ]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pipe_test_pred)

array([[6675,    0,  168,    0],
       [   0, 6589,    0,  493],
       [  27,    0, 5980,  414],
       [   0,    2,    0, 7085]])

In [ ]:
493/(493+6589)*100

6.961310364303869

In [ ]:
168/(168+6675)*100

2.4550635686102584

In [ ]:
(414+27)/(414+27+5980)*100

6.8680890826973995

In [ ]:
2/7085*100

0.028228652081863093

In [ ]:
model.classes_

array([1, 2])